baseURL = 'https://singular-jelly-b03613.netlify.app'
paginate = 6
theme= "coHub"
title = 'FrankSim'

[Languages.en]
languageName = "En"
languageCode = 'en-us'
contentDir = "content/en"

[Languages.fr]
languageName = "Fr"
languageCode = 'fr'
contentDir = "content/fr"
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Meet Frank"
  url= "/meet/"
  weight = 1
  [[menu.Main]]
  name = "Frank's stories"
  url= "/stories/"
  weight = 3
  [[menu.Main]]
  name = "Who we are"
  url= "/about/"
  weight = 4
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 5

  # Sitemap Menu
#  [[menu.sitemap]]
#  name = "Privacy Policy"
#  url = "/privacy/"
#  weight = 1
#  [[menu.sitemap]]
#  name = "Terms"
#  url = "/terms/"
#  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://franksim.com/\" target=\"_blank\">FrankSim </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/favicon.png"
  footerDescription = "Sherbrooke, QC CANADA"

  [params.address]
  address = "Sherbrooke, QC CANADA"
  email = "info@franksim.com"
  #openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  #openingHours = "We are open from 7am — 7pm week days."
  #phone = "+(448) 833 5272 332"

  [params.map]
  #APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  #latitude = "45.4502528"
  #longitude = "-122.783407"
  #pinImage = "images/pin.png"

  # Social icons
#  [[params.social]]
#  icon = "ti-facebook"
#  url = "https://www.facebook.com/"
#  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/franksim2022"
  weight = 2
    [[params.social]]
  icon = "ti-linkedin"
  url = "https://www.linkedin.com/company/franksim/"
  weight = 3
#  [[params.social]]
#  icon = "ti-dribbble"
#  url = "https://dribbble.com/"
#  weight = 3
[[params.social]]
icon = "ti-youtube"
url = "https://www.youtube.com/@FrankSim2022"
weight = 4
  
  
